spring.application.name=sistema-gestion
# Configuración de la conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_sistema_gestion?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# CAMBIA 'tu_contraseña' por la que le pusiste en la instalación (ej: 1234 o root)
spring.datasource.password=1234

# Configuración de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect